{
    "drinks"; [
    {
    "idDrink": "15182",
    "strDrink": "After sex",
    "strDrinkAlternate": null,
    "strTags": null,
    "strVideo": null,
    "strCategory": "Ordinary Drink",
    "strIBA": null,
    "strAlcoholic": "Alcoholic",
    "strGlass": "Highball glass",
    "strInstructions": "Pour the vodka and creme over some ice cubes in a tall glass and fill up with juice. to make it beuty full make the top of the glass with a grenadine and sugar",
    "strInstructionsES": null,
    "strInstructionsDE": "Gießen Sie den Wodka und die Sahne über einige Eiswürfel in ein hohes Glas und füllen Sie ihn mit Saft. Damit es voll ist, verzieren Sie die Oberseite des Glases mit einer Grenadine und Zucker.",
    "strInstructionsFR": null,
    "strInstructionsIT": "Versare la vodka e la crema su alcuni cubetti di ghiaccio in un bicchiere alto e riempire di succo.\r\nPer renderlo bello, versare nella parte superiore del bicchiere un po’ di granatina e nei bordi mettere un po’ di zucchero",
    "strInstructionsZH-HANS": null,
    "strInstructionsZH-HANT": null,
    "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/xrl66i1493068702.jpg",
    "strIngredient1": "Vodka",
    "strIngredient2": "Creme de Banane",
    "strIngredient3": "Orange juice",
    "strIngredient4": null,
    "strIngredient5": null,
    "strIngredient6": null,
    "strIngredient7": null,
    "strIngredient8": null,
    "strIngredient9": null,
    "strIngredient10": null,
    "strIngredient11": null,
    "strIngredient12": null,
    "strIngredient13": null,
    "strIngredient14": null,
    "strIngredient15": null,
    "strMeasure1": "2 cl ",
    "strMeasure2": "1 cl ",
    "strMeasure3": null,
    "strMeasure4": null,
    "strMeasure5": null,
    "strMeasure6": null,
    "strMeasure7": null,
    "strMeasure8": null,
    "strMeasure9": null,
    "strMeasure10": null,
    "strMeasure11": null,
    "strMeasure12": null,
    "strMeasure13": null,
    "strMeasure14": null,
    "strMeasure15": null,
    "strImageSource": null,
    "strImageAttribution": null,
    "strCreativeCommonsConfirmed": "No",
    "dateModified": "2017-04-24 22:18:22"
    },
    {
    "idDrink": "14360",
    "strDrink": "Absolut Sex",
    "strDrinkAlternate": null,
    "strTags": null,
    "strVideo": null,
    "strCategory": "Shot",
    "strIBA": null,
    "strAlcoholic": "Alcoholic",
    "strGlass": "Old-fashioned glass",
    "strInstructions": "Shake Absolut Kurant, Midori, and Cranberry juice in shaker with ice: Strain into rocks glass: Splash of seven on top.Absolut Sex.",
    "strInstructionsES": null,
    "strInstructionsDE": "Absolut Kurant, Midori und Preiselbeersaft im Shaker mit Eis schütteln: In ein Rocks Glas abseihen: Ein Spritzer von 7 oben drauf. Absoluter Sex.",
    "strInstructionsFR": null,
    "strInstructionsIT": "Shakerare Absolut Kurant, Midori e il succo di mirtillo rosso in uno shaker con ghiaccio",
    "strInstructionsZH-HANS": null,
    "strInstructionsZH-HANT": null,
    "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/xtrvtx1472668436.jpg",
    "strIngredient1": "Absolut Kurant",
    "strIngredient2": "Midori melon liqueur",
    "strIngredient3": "Cranberry juice",
    "strIngredient4": "Sprite",
    "strIngredient5": null,
    "strIngredient6": null,
    "strIngredient7": null,
    "strIngredient8": null,
    "strIngredient9": null,
    "strIngredient10": null,
    "strIngredient11": null,
    "strIngredient12": null,
    "strIngredient13": null,
    "strIngredient14": null,
    "strIngredient15": null,
    "strMeasure1": "3/4 oz ",
    "strMeasure2": "3/4 oz ",
    "strMeasure3": "1 oz ",
    "strMeasure4": "1 splash ",
    "strMeasure5": null,
    "strMeasure6": null,
    "strMeasure7": null,
    "strMeasure8": null,
    "strMeasure9": null,
    "strMeasure10": null,
    "strMeasure11": null,
    "strMeasure12": null,
    "strMeasure13": null,
    "strMeasure14": null,
    "strMeasure15": null,
    "strImageSource": null,
    "strImageAttribution": null,
    "strCreativeCommonsConfirmed": "No",
    "dateModified": "2016-08-31 19:33:56"
    },
    {
    "idDrink": "12754",
    "strDrink": "Sex on the Beach",
    "strDrinkAlternate": null,
    "strTags": "IBA,ContemporaryClassic",
    "strVideo": null,
    "strCategory": "Ordinary Drink",
    "strIBA": "Contemporary Classics",
    "strAlcoholic": "Alcoholic",
    "strGlass": "Highball glass",
    "strInstructions": "Build all ingredients in a highball glass filled with ice. Garnish with orange slice.",
    "strInstructionsES": null,
    "strInstructionsDE": "Alle Zutaten in einem mit Eis gefüllten Highball-Glas geben. Mit einer Orangenscheibe garnieren.",
    "strInstructionsFR": null,
    "strInstructionsIT": "Metti tutti gli ingredienti in un bicchiere highball pieno di ghiaccio. Guarnire con fetta d'arancia.",
    "strInstructionsZH-HANS": null,
    "strInstructionsZH-HANT": null,
    "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/lijtw51551455287.jpg",
    "strIngredient1": "Vodka",
    "strIngredient2": "Peach schnapps",
    "strIngredient3": "Cranberry juice",
    "strIngredient4": "Grapefruit juice",
    "strIngredient5": null,
    "strIngredient6": null,
    "strIngredient7": null,
    "strIngredient8": null,
    "strIngredient9": null,
    "strIngredient10": null,
    "strIngredient11": null,
    "strIngredient12": null,
    "strIngredient13": null,
    "strIngredient14": null,
    "strIngredient15": null,
    "strMeasure1": "1 oz ",
    "strMeasure2": "3/4 oz ",
    "strMeasure3": null,
    "strMeasure4": null,
    "strMeasure5": null,
    "strMeasure6": null,
    "strMeasure7": null,
    "strMeasure8": null,
    "strMeasure9": null,
    "strMeasure10": null,
    "strMeasure11": null,
    "strMeasure12": null,
    "strMeasure13": null,
    "strMeasure14": null,
    "strMeasure15": null,
    "strImageSource": null,
    "strImageAttribution": null,
    "strCreativeCommonsConfirmed": "No",
    "dateModified": "2016-07-21 10:12:45"
    }
    ]
    }